### ISSUE TITLE
Template does not work

### ISSUE THREAD

**Issue by jvinters** [Aguafrommars/Templates#315]
## Problem

After installing the template and running 'dotnet new tisduende -o TheIdServer' the UI does not work out of the box. 

## Exception 1
`ApplicationBuilderExtensions.cs:97` throws `KeyNotFoundException `with the message `The given key 'persistAuthorization' was not present in the dictionary.` 

I can temporarily disable SwaggerUI in `appsettings.json` (EnableOpenApiDoc) and it'll run

## Exception 2
If I try navigating to any page a error popup displays `An unhandled exception has occurred. See browser dev tools for details. [Reload](https://localhost:5443/)`

Console displays this error

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Error: Aguacongas.TheIdServer.BlazorApp.Pages.Apis.dll must be marked with 'BlazorWebAssemblyLazyLoad' item group in your project file to allow lazy-loading.
Error: Aguacongas.TheIdServer.BlazorApp.Pages.Apis.dll must be marked with 'BlazorWebAssemblyLazyLoad' item group in your project file to allow lazy-loading.
```

@aguacongas Any idea how I can solve this and get the app running?

**Comment by aguacongas** [comment]
did you chek this answer : https://github.com/Aguafrommars/Templates/issues/283#issuecomment-2027984990

**Comment by EversongWoods** [comment]
@aguacongas My project upgrade to 5.0.1 but the ```Exception2``` still happened! there are the screenshots！
![屏幕截图 2024-09-15 115020](https://github.com/user-attachments/assets/cb606adf-6f5e-43a7-8569-58068a316ef1)
![屏幕截图 2024-09-15 115048](https://github.com/user-attachments/assets/5b0193a1-9dc1-48c2-aaee-73b7882ff7a1)

**Comment by aguacongas** [comment]
In 'App.razor.cs' replace *.dll* by *.wasm*

**Comment by aguacongas** [comment]
fixed in release [5.0.2](https://github.com/Aguafrommars/Templates/releases/tag/5.0.2)

**Comment by EversongWoods** [comment]
@aguacongas The problem still exists, I think there may be other problems
